= Atelier B - tools

In this repo contains some simple bash script that that helps manage the Atelier B projects esier.

== Introduction

TODO

== List of tools

=== startBB-2404.sh

This bash script starts a bbatch console. You can use this script for Atelier B 204.04.2.

==== Prerequisites

* Installed Atelier B 24.04.2.

* The workspace directory contains its config file (AtelierB).

==== Usage

Put this file in a directory that is in the $PATH environment variable, or create a simbolic link here.

You can run this script form an Atelier B workspace directory that contains the project directories, the _bdb_ database directory and the workspce config file (AtelierB). If the workspace directory doesn't contain a file named _AtelierB_, the script will exit immediately.

=== initABWS-2404.sh

This bash script makes an Atelier B workspace directory form an empty directory. It will create the _bdb_ database folder, and a config file named _AtelierB_ for this workspace. 

==== Prerequisites

* Installed Atelier B 24.04.2.

* The directory is empty

==== Usage

Put this file in a directory that is in the $PATH environment variable, or create a simbolic link here.

You can run this script from an empty directory. If the directory is not empty the script will exit immediately. The script will ask the path of the installed Atelier B.

